### PR TITLE
Fix for issue number #57

### PR DESCRIPTION
**Pull request by Polaris000**
Steps:

- [x] copied folder [img/favicon](https://github.com/grimoirelab/grimoirelab.github.io/tree/master/img/favicon) from [grimoirelab.github.io](https://github.com/grimoirelab/grimoirelab.github.io) into grimoirelab-tutorial/images

### CODE REVIEW

**Comment by Polaris000** [comment]
I thought of this because the grimoirelab.github.io site redirected to [the grimoirelab homepage](https://chaoss.github.io/grimoirelab/) where I realized that a favicon appeared.

**Comment by Polaris000** [comment]
@jgbarah please have a look.

**Comment by jgbarah** [comment]
Sorry for being late with this.

Did you check that this enough for the favicon to be served?

**Comment by Polaris000** [comment]
Good thing you asked!! I had a small chrome cache problem which was showing the favicon of grimoire-lab.github.io. 
I have fixed the path for fetching the favicon.ico file. I'll send you a screenshot for confirmation

**Comment by Polaris000** [comment]
screenshot from 2019-02-15 22-06-40

**Comment by Polaris000** [comment]
Also, could you have a look at [pr  #60 ](https://github.com/chaoss/grimoirelab-tutorial/pull/60) ?

**Pull request merged**
