### PR TITLE
[docs] Cleaning up tutorial files

### PR DESCRIPTION
**Pull request by VSevagen**
This commit serves to clean up redundant data or
data that has already been ported to their relevant
repositories

Signed-off-by: sevagenv <sevagenv@gmail.com>

### CODE REVIEW

**Comment by VSevagen** [comment]
The `perceval` and `internal` docs have already been ported and the `sortinghat` docs I think are redundant.
The `_layout` and `_includes` will not be needed in the new tutorial as everything can be handled through markup and jekyll plugins instead.

**Comment by VSevagen** [comment]
I'll be updating this PR as I port the other docs their respective repo

**Comment by VSevagen** [comment]
@vchrombie regarding the `Reporting with Manuscript` section in the tutorial, it seems the README of the GrimoireLab Manuscript have the same docs. If so, can I remove that section too ?

**Review by vchrombie — CHANGES_REQUESTED** [review]
Thanks for opening the PR @VSevagen.

I understand most of them are html files, perceval content has been ported to the repo and the old sortinghat content is not relevant now. But, I would still make the PR short with changing few files at a time. This would make the reviewing task easy and we would leave any chance of missing any relevant piece of information.

Also, I wouldn't remove the scripts entirely. We can have them here, and we can write some small explanations related to it. WDYT?

**Comment by VSevagen** [comment]
> I would still make the PR short with changing few files at a time. This would make the reviewing task easy and we would leave any chance of missing any relevant piece of information.

I understand. I've updated the PR with the unnecessary html files at the moment

> Also, I wouldn't remove the scripts entirely. We can have them here, and we can write some small explanations related to it. WDYT?

Ok. I've excluded the docs for now.

**Review by vchrombie — APPROVED** [review]
LGTM! I have rebased the PR, merging it.

**Pull request merged**
