### PR TITLE
[config] Updated the link in the footer to master

### LINKED ISSUE #195: Update the `gh_edit_branch` configuration
The `Edit this page on GitHub` link in the footer of every page redirects to the `tesseract` branch of the repository. The `_config.yml` must be updated to point it to the current `master` branch.

### PR DESCRIPTION
**Pull request by and3rcg**
Fixes #195

There was an issue with the [_config.yml](https://github.com/chaoss/grimoirelab-tutorial/blob/master/_config.yml) file that was generating a link to the [tesseract](https://github.com/chaoss/grimoirelab-tutorial/tree/tesseract) branch instead of the intended [master](https://github.com/chaoss/grimoirelab-tutorial/tree/master) branch.

### CODE REVIEW

**Comment by vchrombie** [comment]
Thanks for opening the PR @and3rcg

Do you mind fixing the sign-off issue?
https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions

Also, it would be great if you can update the commit message too according to the guidelines
https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages

You can amend the commit and fix both the issues at once
```
$ git commit --amend -s
```
Please let us know if you need any help

**Comment by and3rcg** [comment]
Unfortunately I won't be able to do it right now, but I will as soon as I can. I apologize for the lack of experience.

**Comment by vchrombie** [comment]
> Unfortunately I won't be able to do it right now, but I will as soon as I can. I apologize for the lack of experience.

No issues at all, feel free to do it when you have time. Let us know if you need help.
Thanks.

**Comment by vchrombie** [comment]
> @vchrombie I think I managed to fix my PR and commit issues, waiting for review now. Thank you for the guidance.

Thanks for working on it. The PR looks great but I have a small suggestion.

Do you mind splitting the commit description into multiple lines? We follow a convention to wrap the body to 72 characters in each line. You need not calculate it but you can approximately break it.
https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages

I would suggest changing it something like this
```
Update the github edit branch link to master

The _config.yml file has a gh_edit_branch variable that was pointing
to the unintended tesseract branch. This commit updated that variable
so that it now points to the master branch.

Resolves: https://github.com/chaoss/grimoirelab-tutorial/issues/195
Signed-off-by: Anderson Caminha <geo.anders1@gmail.com>
```

I hope this helps. Please let me know if you need any help.

**Review by vchrombie — APPROVED** [review]
LGTM!
Thank you for the work @and3rcg.

**Comment by vchrombie** [comment]
> Thank you for the guidance! I'm looking forward to contributing more to this and other projects!

You are welcome and we look forward to your contributions.

**Pull request merged**
