### PR TITLE
fix minor typos and broken links in the tutorials

### PR DESCRIPTION
**Pull request by vchrombie**
I was going through the sirmordred tutorials and found some typos. Please let me know if there are any more changes to do. :slightly_smiling_face: 

Signed-off-by: Venu Vardhan Reddy Tekula <venuvardhanreddytekula8@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
I think I caught a few more typos. Instead of making a new commit and a new PR again, maybe I will send them here itself.

I would send the patches asap.

Thanks. :)

**Comment by valeriocos** [comment]
Thanks @vchrombie ! I wait for more commits then :)

**Comment by vchrombie** [comment]
Hi @valeriocos 

I think I am done with the corrections and sent the commits accordingly. Please let me know if there is anything to revert back or anything to add more.

I have sent 4 commits accordingly. Please let me know if I have to squash all into one commit.

**Comment by valeriocos** [comment]
That's perfect like this @vchrombie , thanks!

**Pull request merged**
