### PR TITLE
Fix Markdown syntax for link

### PR DESCRIPTION
**Pull request by dplanella**

### CODE REVIEW

**Comment by dplanella** [comment]
@jgbarah thanks! Provided the sign-off.

Is there a way to comply with the DCO without having to clone a local copy? For one-liners like this, it's a bit of a barrier to contribution, as the DCO bot prevents using the GitHub web UI to submit quick changes.

**Comment by dplanella** [comment]
Nevermind, I found out you can also sign off from the web UI :-)

https://github.com/chaoss/grimoirelab-tutorial/blob/master/contributing.md#dco-and-sign-off-for-contributions

**Comment by GeorgLink** [comment]
Hi @dplanella, 
We know that the DCO can be a pain. It trips me up as well.
Have you tried this browser plugin? It makes my life easier.
https://github.com/scottrigby/dco-gh-ui

**Comment by dplanella** [comment]
Thanks for the tip @GeorgLink!

**Pull request merged**
