### PR TITLE
Move image to correct directory & update

### PR DESCRIPTION
**Pull request by RCheesley**
Apologies, realised that the image was in the wrong location and that's what was causing the broken link.

Deleted it from the top-level assets folder and uploaded to the figs directory in the basics folder where the other images are saved.

Hopefully that should fix it!

### CODE REVIEW

**Comment by RCheesley** [comment]
> @RCheesley can you squash the commits in just one? thanks

I don't think I can do that on the Github UI (will take a look), if not I'll pull it down and try to figure out how to do it locally this evening! Always learning!

**Comment by valeriocos** [comment]
OK no worries @RCheesley , it would be great if you can give it a try. If you have any issue, we can merge it as it is.

Find below some info, hope they help.

On top of this same page, there is a button `fork`, click it to fork the repo in your GitHub profile.

In your terminal, type the following: 
```
cd /home
git clone https://github.com/RCheesley/grimoirelab-tutorial
```
this will clone the forked repo in your /home/

```
cd grimoirelab-tutorial (enter to the directory where the repo has been cloned)
git checkout -b my-branch master
```
this will create a branch where you can work on your changes

...modify the files you need

```
git status
```
 this will prompt the files you touched (e.g., modified, added, deleted)

```
git add <path-of-the-touched-file>
``` 
this will add the files that are going to be included in the next commit. You can call this command for each file you modified

```
git commit
```
this will enable you to create a commit containing the files added with the previous instruction, in the new editor you can add a title and message. Alternatively, you can call:

```
git commit -m "my-commit-title/message"
```
This won't redirect you to the new editor

```
git show
```
this will allow you to check the last commit added

```
git push https://github.com/RCheesley/grimoirelab-tutorial
```
this command will push the commit to your fork. Automatically, GitHub will detect it and you can finally click the button to open the PR.

**Comment by RCheesley** [comment]
Thanks, I was just being lazy by making these small changes when I noticed them via the Github UI rather than cloning down the repo etc (as I was doing it while I was following the tutorial so I had many other things on my mind!). I'll look at it later!

**Comment by valeriocos** [comment]
Hi @RCheesley , how is it going with this PR, should we merge it?

**Comment by GeorgLink** [comment]
Thanks @RCheesley 

> Agreed that it could be a single commit. 

We can always "squash merge" a pr to combine all commits into a single commit.

**Comment by RCheesley** [comment]
Sorry I didn't get around to it as have been pretty hectic!

**Comment by valeriocos** [comment]
no worries @RCheesley , thank you for the PR ! :)

**Pull request merged**
