### PR TITLE
[docs] Add community health section

### PR DESCRIPTION
**Pull request by VSevagen**
This commit adds the initial files related to the
community health sections. Each section will be created
as another directory with its own assets within community-health.

Signed-off-by: sevagenv <sevagenv@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
Thanks for the PR @VSevagen. The PR looks good.

> Each section will be created as another directory with its own assets within community-health.

I didn't understand this point, can you elaborate the file structure?
If each section would have a separate folder within community-health, how do we store the files in this PR?

I think I took a long vacation and forgot most of things 😅. Do you mind adding some referernce?

**Comment by vchrombie** [comment]
Also, please rebase the PR when you have time.

**Comment by VSevagen** [comment]
> Thanks for the PR @VSevagen. The PR looks good.
> 
> > Each section will be created as another directory with its own assets within community-health.
> 
> I didn't understand this point, can you elaborate the file structure? If each section would have a separate folder within community-health, how do we store the files in this PR?
> 
> I think I took a long vacation and forgot most of things sweat_smile. Do you mind adding some referernce?


├── community-health
│   ├── contributions.md
│   └── time.md
│   ├── people.md
│   └── code-development-activities.md
│   ├── code-development-efficiency.md
│   └── issue-resolution.md
│   └── index.md

The above is the current structure of this pr. The next pr will be adding folders to this structure, for example `Contributions` and then it will contain the subsections to `contributions.md`.

The reason why i didn't add the above files into their respective folder directly is because they act an `index.md` for their respective subsection and I wanted all supposedly index files to be on the same level.

**Review by vchrombie — APPROVED** [review]
LGTM!

**Pull request merged**
