### PR TITLE
Fixed Typo Error

### PR DESCRIPTION
**Pull request by WasimAkhtarKhan**
Signed-off-by: Wasim Akhtar Khan <wasimkhan03150@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @WasimAkhtarKhan, thanks for the PR. The CHAOSS Charter requires that contributions are accompanied by a Developer Certificate of Origin sign-off. For ensuring it, a bot checks all incoming commits.
https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions

Please add the signoff for the commit. Let us know if you need help.

**Review by WasimAkhtarKhan — COMMENTED** [review]
Signed-off-by: Wasim Akhtar Khan <wasimkhan03150@gmail.com>

**Comment by WasimAkhtarKhan** [comment]
> Hi @WasimAkhtarKhan, thanks for the PR. The CHAOSS Charter requires that contributions are accompanied by a Developer Certificate of Origin sign-off. For ensuring it, a bot checks all incoming commits.
> https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions
> 
> Please add the signoff for the commit. Let us know if you need help.

Hello @vchrombie , I have edited the commit message but DCO is not rechecking it.
If there's anything I should be doing, please tell me.

**Comment by vchrombie** [comment]
Hi @WasimAkhtarKhan, I see you have edited the PR description. But, that's not what is required.
You have to amend the commit with the signoff and force push the branch to see the changes here. You might need to use the CLI.

```
$ git clone https://github.com/WasimAkhtarKhan/grimoirelab-tutorial/
$ cd grimoirelab-tutorial/
$ git checkout patch-1
$ git commit --amend --signoff
$ git push -f origin patch-1
```
Let me know If you need any help.

**Comment by WasimAkhtarKhan** [comment]
> Hi @WasimAkhtarKhan, I see you have edited the PR description. But, that's not what is required.
> You have to amend the commit with the signoff and force push the branch to see the changes here. You might need to use the CLI.
> 
> ```
> $ git clone https://github.com/WasimAkhtarKhan/grimoirelab-tutorial/
> $ cd grimoirelab-tutorial/
> $ git checkout patch-1
> $ git commit --amend --signoff
> $ git push -f origin patch-1
> ```
> 
> Let me know If you need any help.

Done @vchrombie 
I got it and will make sure this doesn’t happen again.
Thanks

**Comment by vchrombie** [comment]
Thanks for working on this PR.

>  I got it and will make sure this doesn’t happen again.

No problem. :slightly_smiling_face:

**Review by vchrombie — APPROVED** [review]
LGTM

**Pull request merged**
