### PR TITLE
Fixed a link to sirmordred readme

### PR DESCRIPTION
**Pull request by abhiandthetruth**
Signed-off-by: abhiandthetruth <abhiandthetruth@gmail.com>
Linked to issue 
https://github.com/chaoss/grimoirelab-sirmordred/issues/433

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @abhiandthetruth 
I have an idea. 

Let's keep this PR open for a few days, and we will all hunt for the broken links. Maybe we can comment them over here and send a single in the end, fixing all of them. 

@valeriocos @imnitishng @animeshk08 
Please let me know your opinions.

**Comment by animeshk08** [comment]
I am up for it let the hunt begin :)

**Comment by imnitishng** [comment]
Great! I'll get on it!

**Comment by imnitishng** [comment]
Found one [here](https://chaoss.github.io/grimoirelab-tutorial/sirmordred/micro-mordred.html#what-is-mordred).

> What is Mordred?
> Mordred is the tool used to orchestrate the execution of the GrimoireLab platform, via a configuration file. We can find more details about the sections in the configuration file [here](https://github.com/chaoss/grimoirelab-sirmordred#setupcfg).
> 

`here` points to a broken link, needs to be pointing [here](https://github.com/chaoss/grimoirelab-sirmordred#setupcfg-).

**Comment by imnitishng** [comment]
Not a broken link, but seems like making `here`

> The above command requires two files:
> 
> setup.cfg: Contains section of configuration for different components and tools
> projects.json: Contains a list of projects to analyze
> Read more about the projects file [here](https://github.com/chaoss/grimoirelab-tutorial/blob/master/sirmordred/projects.md).
> 
> We’ll (for the purpose of this tutorial) use the files provided in the /utils directory, but feel free to play around with the file and their configurations :)

point to the detailed [README section](https://github.com/chaoss/grimoirelab-sirmordred#projectsjson-) would be a better option.

**Comment by imnitishng** [comment]
@vchrombie @animeshk08 I think we should move this discussion to the [issue](https://github.com/chaoss/grimoirelab-sirmordred/issues/433) because @abhiandthetruth has already made multiple PRs.
Let me know your opinions.
@valeriocos WDYT?

**Comment by animeshk08** [comment]
There's already an issue opened we can use it: https://github.com/chaoss/grimoirelab-sirmordred/issues/433

I think we move the discussion there :)

**Comment by abhiandthetruth** [comment]
> Found one [here](https://chaoss.github.io/grimoirelab-tutorial/sirmordred/micro-mordred.html#what-is-mordred).
> 
> > What is Mordred?
> > Mordred is the tool used to orchestrate the execution of the GrimoireLab platform, via a configuration file. We can find more details about the sections in the configuration file [here](https://github.com/chaoss/grimoirelab-sirmordred#setupcfg).
> 
> `here` points to a broken link, needs to be pointing [here](https://github.com/chaoss/grimoirelab-sirmordred#setupcfg-).

That is the one I fixed :)

**Comment by abhiandthetruth** [comment]
Since you all  are hunting for the links let me tell you what I did
I opened the folder in vscode searched `https://github.com/chaoss/grimoirelab-sirmordred` and fixed any links that needed a change which was one in this case. If you are trying please think of any links that may get excluded by the above process :). I think that this pr should fix all the links related to the back-link pr though.

**Comment by valeriocos** [comment]
Thank you all! I understand that this PR can be merged and you agreed on moving the discussions to https://github.com/chaoss/grimoirelab-sirmordred/issues/433. 

Please confirm (via emoji or comment), so I can merge the PR. Thanks

**Pull request merged**
