### PR TITLE
removed 'bots_names' param from sample config

### PR DESCRIPTION
**Pull request by abhiandthetruth**
Signed-off-by: abhiandthetruth <abhiandthetruth@gmail.com>

### CODE REVIEW

**Comment by abhiandthetruth** [comment]
Sorry, Yes there is another occurrence. I will check for others. Another thing @valeriocos Is ```aliases_file``` and ```menu_file``` necessary params coz missing the ```aliases_file``` param caused an error on my machine. I was running on docker though. I don't know about the without docker setup.

**Comment by valeriocos** [comment]
Thanks @abhiandthetruth! 

The aliases_file is mandatory (AFAIR), but it should be always present. Can you give more details about your configuration/settings. Which tutorial are you following, the one on sirmordred (https://github.com/chaoss/grimoirelab-sirmordred#getting-started) or the one on grimoirelab (https://github.com/chaoss/grimoirelab#getting-started)?

**Comment by abhiandthetruth** [comment]
removed all instances of bots_names. I was taking a look at the config in this tutorial https://github.com/chaoss/grimoirelab-tutorial/blob/master/sirmordred/dashboard.md the mordred-simple.cfg

**Comment by abhiandthetruth** [comment]
Also the readme at https://github.com/chaoss/grimoirelab-sirmordred doesn't mention it as required.

**Comment by abhiandthetruth** [comment]
Well apparently it was my mistake. What happened was that I didn't defined the parameter ```aliases_file``` under ```[general]``` whose default value is ```./aliases.json``` and since it was not there, there was a file not found error. Sorry :).

**Comment by valeriocos** [comment]
No worries :)

**Comment by abhiandthetruth** [comment]
commits squashed!

**Comment by valeriocos** [comment]
Thanks @abhiandthetruth

**Pull request merged**
