### PR TITLE
Configuration for using Jekyll Documentation Theme.

### PR DESCRIPTION
**Pull request by jgbarah**
Added configuration to use Jekyll Documentation Theme, in a way that should run directly on GitHub Pages, so that we now have the tutorial available as https://chaoss.github.io/grimoirelab-tutorial.

I've tried not to break the GitBook build, but in any case this is the first commit to start a path for
moving to GitHub Pages as the primary reference for the GrimoireLab Tutorial.

Some minor tweaks have been done to the theme, to (hopefully) better suit the needs of the tutorial.

Some minor changes to the tutorial itself have been added too.

To check how the tutorial looks like in GitHub Pages, check out https://jgbarah-chaoss.github.io/grimoirelab-tutorial

### CODE REVIEW

**Comment by acs** [comment]
Cool, this version is more easily editable and it has a search box! And with the top bar it is better integrated with the rest of CHAOSS.

Could we use a CC license for the contents?

In any case, LGTM. Merging it.

**Comment by jgbarah** [comment]
Thanks!!!

> Could we use a CC license for the contents?

https://github.com/chaoss/grimoirelab-tutorial/blob/master/license.md

**Comment by acs** [comment]
> https://github.com/chaoss/grimoirelab-tutorial/blob/master/license.md

But at the bottom of all pages, the license information is:

`©2018 CHAOSS. All rights reserved. 
`

Should we change that?

**Comment by jgbarah** [comment]
Yes, you're right. #25

**Pull request merged**
